name: make-system-user
version: '9'
summary: Make a system user file for auto import
description: Make an auto-import.assert file
  containing required assertions to create a system user
  signed by your registered key

grade: stable
confinement: classic 
base: core18

apps:
    make-system-user:
        command: bin/make_system_user

parts:
    # this part is needed because snapcraft python requires PyYAML built with
    # libYAML bindings so that snapcraft can use C-based loaders it provides
    libyaml:
        plugin: python
        python-version: python3
        source: https://pyyaml.org/download/pyyaml/PyYAML-3.13.tar.gz
        build-environment:
        - C_INCLUDE_PATH: /usr/include/python3.6
        build-packages: 
        - python3-dev
        - libyaml-dev
        override-build: |
            snapcraftctl build
            python3 setup.py --with-libyaml install

    # this part is necessary because snapcraft doesn't correctly migrate the
    # dependencies for the snapcraft package into the final snap, so we 
    # have to manually add all the dependencies
    snapcraft-pip:
        plugin: nil
        source: https://github.com/snapcore/snapcraft.git
        source-tag: "2.42"
        source-depth: 1
        stage-packages: 
        - libapt-pkg-dev
        - libsodium-dev
        override-build: |
            pip3 install -r requirements.txt -t $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages --ignore-installed
    env:
        after: [snapcraft-pip]
        plugin: python
        python-version: python3
        source: .
